#pragma once

#include "CoreMinimal.h"
#include "InventoryItem.h"
#include "FuelSiphonItem.generated.h"

/**
 * Handles fluid transfer between a Source (Vehicle) and Target (Jerry Can).
 * Generates acoustic noise based on flow rate (turbulence).
 */
UCLASS()
class GENOMEPROTOCOL_API UFuelSiphonItem : public UInventoryItem
{
    GENERATED_BODY()

public:
    // --- FLUID DYNAMICS ---

    // Transfer Rate in Liters per Second (The 'Bandwidth')
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Physics")
    float FlowRate = 0.2f;

    // Max distance the hose can stretch before the link breaks
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Physics")
    float MaxHoseLength = 250.0f; // 2.5 meters

    // --- ACOUSTIC SIGNATURE ---

    // Noise generated by liquid sloshing/pumping.
    // Higher flow = Higher noise.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Physics")
    float SiphonNoiseLevel = 1.5f;

    // --- FUNCTION ---

    // Performs the transfer calculation for a single frame (Tick)
    // Returns TRUE if transfer is active, FALSE if empty/full.
    UFUNCTION(BlueprintCallable, Category = "Genome | Actions")
    bool ProcessTransfer(float DeltaTime, float& SourceAmount, float& TargetCurrent, float TargetMax);
};