#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "GenomeCharacter.generated.h"

UCLASS()
class GENOMEPROTOCOL_API AGenomeCharacter : public ACharacter
{
    GENERATED_BODY()

public:
    AGenomeCharacter();

protected:
    virtual void BeginPlay() override;

public:
    // --- BIOLOGICAL SIMULATION VARIABLES ---

    // Total blood volume in Liters (Realism focus)
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Biology")
    float BloodVolume = 5.0f;

    // Localized Health (0.0 = Destroyed, 1.0 = Healthy)
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Biology")
    float Health_Head = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Biology")
    float Health_Torso = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Biology")
    float Health_LeftArm = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Biology")
    float Health_RightArm = 1.0f;

    // --- SENSORY & EMOTION (The Sound Engine Driver) ---

    // Current Heartrate (BPM). Drives the "Heat" sphere radius.
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Genome | Psychology")
    float CurrentHeartrate = 72.0f;

    // Panic Level (0.0 to 1.0). Increases sound leakage and camera shake.
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Genome | Psychology")
    float PanicLevel = 0.0f;

    // --- INFRASTRUCTURE INTERACTION ---

    // Ability to interact with power grids and lab equipment
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Genome | Skills")
    int32 NetworkingSkill = 1;

    // Function to calculate "Heat" generated by the player's presence
    UFUNCTION(BlueprintCallable, Category = "Genome | AI")
    float CalculateAcousticHeat();
};